<script type="text/javascript">
    function importStatusMonitor(){
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/adminhtml_importprogress/check'); ?>', {
            method:     'get',
            onSuccess: function(transport){
                            var response = "";
                            var step = transport.responseJSON.size();
                            transport.responseJSON.forEach(function(element, index, array){
                                index = index+1;
                                response += "<p>"+index+". "+element+"</p>";
                            });
                            if($('loading_mask_loader').select('#icecatlive-response').size() == 0){
                                $('loading_mask_loader').insert({bottom: '<div id="icecatlive-response" style="text-align: left">'+response+'</div>'});
                            }else{
                                $('icecatlive-response').replace('<div id="icecatlive-response" style="text-align: left">'+response+'</div>');
                            }
                            if($('loading_mask_loader').select('#icecatlive-curstep-response').size() == 0){
                                $('icecatlive-response').insert({before: '<p id="icecatlive-curstep-response">Current step: '+step+'/9</div>'});
                            }else{
                                $('icecatlive-curstep-response').replace('<p id="icecatlive-curstep-response">Current step: '+step+'/9</div>');
                            }
                            if(step == 9){
                                $$('#loading_mask_loader > img')[0].setStyle({
                                    'display': 'none'
                                });
                                var str = $('loading_mask_loader').innerHTML;
                                str = str.replace('<br>Please wait...', '');
                                $('loading_mask_loader').innerHTML = str;
                                $('icecatlive-response').replace('<div id="icecatlive-response" style="text-align: left">'+response+'</div><br><button id="icecatlive_button_finish" onclick="javascript:hide_progress_popup(); return false;" title="Finish import" type="button" class="scalable " style=""><span><span><span>Finish import</span></span></span></button>');
                                clearInterval(timerId);
                            }

                        }
        });
    }
    function check() {
        $('loading_mask_loader').setStyle({
            width: '430px',
            marginLeft: '-235px',
            top: '25%'
        });
        $('loading-mask').setStyle({
            opacity: '0.90'
        });
        $$('#loading_mask_loader > img')[0].setStyle({
            'display': 'inline'
        });
        timerId = setInterval("importStatusMonitor()", 5000);
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){
                if (transport.responseText){
                    alert(transport.responseText);
                    clearInterval(timerId);
                    $('loading-mask').setStyle({
                        'display': 'none'
                    });
                }
            },
            onComplete: function(transport){
                    clearInterval(timerId);
                    $('loading_mask').setStyle({
                        'display': 'block'
                    });
            }
        });
    }
    function hide_progress_popup(){
        $('loading-mask').setStyle({
            display: 'none'
        });
        $('icecatlive-curstep-response').remove();
        $('icecatlive-response').remove();
        $('icecatlive_button_finish').remove();
    }
    $('config_edit_form').on('change', '.input-text, .select', function(event) {
        if(!$('icecatlive-saveconfig')){
            $('icecatlive_button').writeAttribute('disabled', 'disabled');
            $('icecatlive_button').addClassName('disabled');
            $('icecatlive_button').insert({before: '<p id="icecatlive-saveconfig">Please save configuration, and after start import</p>'});
        }
    });
</script>
<?php echo $this->getButtonHtml(); ?>